<script>
	import { nebulaLogoWhite, blackholeHeroEnhanced } from '$lib'
	const {
		background = {
			alt: 'A quasi-black hole',
			file: blackholeHeroEnhanced,
		},
		sronIcon = nebulaLogoWhite,
		paragraph,
		pageTitle = 'None set',
		titleColor,
	} = $props()

	// Validation to prevent empty alt text
	if (!background.alt || background.alt.trim() === '') {
		throw new Error('The "background.alt" prop must be a non-empty string.')
	}
</script>

<section class="hero">
	<div class="content-container">
		{#if paragraph}
			<p class="subheading">{paragraph}</p>
		{/if}
		{#if background.file}
			<enhanced:img
				src={background.file}
				alt={background.alt}
				class="hero-bg"
				sizes="100vw"
				fetchpriority="high" />
		{/if}
		{#if sronIcon}
			<img src={sronIcon} alt="Logo of SRON Academy" class="hero-logo" />
		{/if}
		<h1 class="title" style={titleColor && `color: ${titleColor}`}>
			{pageTitle}
		</h1>
	</div>
</section>

<style>
	.hero {
		--menu-button-size: 3.75rem;
		border-bottom: 0.375rem solid var(--cleanroom-100);
		position: relative;
		padding: 1.5rem;
		padding-top: 5.25rem;
		@media (min-width: 56.25rem) {
			padding: 3.5rem 4rem 2.25rem 0.5rem;
		}

		/* every adjecent elem should have margin-top; except for the picture as that is the background image. */
		> *:not(picture) + *:not(picture) {
			margin-top: 1rem;
		}

		/* if a p is present the logo will correctly get margin-top */
		> p ~ img {
			margin-top: 1rem;
		}

		/* picture does not exist but is generated by enhanced:img, thus this line does work */
		picture {
			display: contents;

			enhanced\:img {
				position: absolute;
				top: 0;
				left: 0;
				width: 100%;
				height: 100%;
				object-fit: cover;
				object-position: center;
				z-index: -1;
			}
		}

		.hero-logo {
			width: clamp(12.5rem, 7.15rem + 28.5vw, 25rem);
			max-width: 36.375rem;
			display: block;
		}

		@media (min-width: 56.25rem) {
			h1 {
				padding-left: 3.5rem;
			}
		}
	}
</style>
