<script>
	import { NebulaLogo, nebulaLogoWhite, blackholeHeroEnhanced } from '$lib'

	const {
		attribution = {
			text: '',
			link: '',
		},
		background = {
			alt: 'A quasi-black hole',
			file: blackholeHeroEnhanced,
		},
		sronIcon = nebulaLogoWhite,
		logoColor = '#fff',
		paragraph,
		pageTitle = 'None set',
		titleColor,
		fullScreen = false, // This property makes the banner photo take up nearly the whole screen.
		logoOverlay = false, // This property gives the banner logo a blue background for better contrast
		bottomLayout = false, // This property sets an alternative layout where both the logo and title are at the bottom
		focalPoint = 'center', // This property sets the focal point of the banner image
	} = $props()

	// Validation to prevent empty alt text
	if (!background.alt || background.alt.trim() === '') {
		throw new Error('The "background.alt" prop must be a non-empty string.')
	}
</script>

<section
	class="hero {fullScreen ? 'fullscreen' : ''} {bottomLayout
		? 'bottom-layout'
		: ''}"
	style="--_focal-point: {focalPoint}">
	{#if paragraph}
		<p class="subheading">{paragraph}</p>
	{/if}
	{#if background.file}
		<figure>
			<enhanced:img
				src={background.file}
				alt={background.alt}
				class="hero-bg"
				sizes="100vw"
				fetchpriority="high" />
			{#if attribution.link != ''}
				<figcaption>
					<a href={attribution.link} rel="external">
						<span class="visually-hidden">Image attribution:</span>
						{attribution.text ? attribution.text : attribution.link}
					</a>
				</figcaption>
			{/if}
		</figure>
	{/if}
	<div class="content-container">
		<div class="logo-container {logoOverlay ? 'logo-overlay' : ''}">
			<div class="content-container-alt">
				{#if sronIcon}
					<NebulaLogo color={logoColor} title="Nebula Xplorer Logo" />
				{/if}
				<h1 class="title" style={titleColor && `color: ${titleColor}`}>
					{pageTitle}
				</h1>
			</div>
		</div>
	</div>
</section>

<style>
	.hero {
		position: relative;
		padding-block: 3.5rem 2.25rem;
		border-block-end: 0.375rem solid var(--accent-color);

		@media (min-width: 56.25rem) {
			&.fullscreen {
				padding-block-start: 30vh;
			}
		}

		/* every adjacent element should have margin-top; except for the picture as that is the background image. */
		> *:not(picture) + *:not(picture) {
			margin-block-start: 1rem;
		}

		/* if a p is present the logo will correctly get margin-top */
		> p ~ img {
			margin-block-start: 1rem;
		}

		/* picture does not exist but is generated by enhanced:img, thus this line does work */
		picture {
			display: contents;

			enhanced\:img {
				position: absolute;
				top: 0;
				left: 0;
				width: 100%;
				height: 100%;
				object-fit: cover;
				object-position: var(--_focal-point);
				z-index: -1;
			}
		}

		figcaption {
			position: absolute;
			bottom: 0;
			right: 0;
			background: rgba(0, 0, 0, 0.493);
			padding: 0.5em;

			a:hover {
				text-decoration: underline;
			}
		}

		h1 {
			padding-block-start: 0.25em;
		}

		:global(svg) {
			display: block;
			width: clamp(12.5rem, 7.15rem + 28.5vw, 25rem);
			max-width: 36.375rem;
		}
	}

	figcaption {
		position: absolute;
		bottom: 0;
		right: 0;
		background: rgba(0, 0, 0, 0.493);
		padding: 0.5em;

		a:hover {
			text-decoration: underline;
		}
	}

	.logo-overlay {
		--_space-mid-opacity: hsla(238, 35%, 15%, 0.75);

		padding: 2em;
		width: min-content;
		background-color: var(--_space-mid-opacity);
	}

	/* Alternate layout */
	.bottom-layout {
		padding-inline: 0;
		padding-block: 10rem 0;

		@media (min-width: 56.25rem) {
			padding-block: 50vh 0;
		}

		h1 {
			padding-block: 0.5em;
		}

		.content-container-alt {
			width: 100%;
			max-width: var(--content-width);
			margin-inline: auto;
			margin-block: 0;
			display: flex;
			align-items: center;
			flex-wrap: wrap;
			column-gap: calc(1em + 2vw);
		}

		.logo-container {
			width: 100%;
			padding-block: 0;
			margin-inline: 0;

			@media (min-width: 56.25rem) {
				padding-block-start: 4rem;
			}
		}

		.logo-overlay {
			background: linear-gradient(
				transparent 0%,
				var(--_space-mid-opacity) 40%,
				var(--background-color-dark)
			);
		}

		.content-container {
			max-width: unset;
		}

		:global(svg) {
			font-size: clamp(2.5rem, 5vw + 1rem, 4.375rem);
			line-height: clamp(2.5rem, 5vw + 1rem, 4.625rem);
			height: 2.5lh;
			width: auto;
			padding-block: 0.5em;
		}
	}
</style>
